version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

  # MongoDB express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb  # MongoDB service name
    depends_on:
      - mongodb

  # ActiveMQ service
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616" # JMS protocol connections
      - "8161:8161" # ActiveMQ Web Console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 2048
    volumes:
      - activemq_data:/data

volumes:
  mongo_data:
  activemq_data:
