spring:
  main:
    web-application-type: none
  data:
    mongodb:
      authentication-database: admin
      database: order
      host: localhost
      port: 27017
      username: admin
      password: admin

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

grpc:
  server:
    port: 7090